### ISSUE TITLE
CLI support

### ISSUE THREAD

**Issue by mk-emeks** [emeks-studio/colorin-colorado#7]
Provide a REPL or a console client in order to support flags and options for the current executable.

**Comment by mirko-plowtech** [comment]
- Proposed lib: https://hackage.haskell.org/package/turtle-1.6.1/docs/Turtle-Options.html (options)

  - lib tutorial: https://hackage.haskell.org/package/turtle-1.6.1/docs/Turtle-Tutorial.html

- Nix tip (not related to the task):


Suppose we want to use haskell as our scripting language (instead of bash, ruby or python)

1. In a file called: `haskell-script.sh` :
```haskell
#! /usr/bin/env nix-shell
#! nix-shell --pure -i runghc -p "haskellPackages.ghcWithPackages (pkgs: [ pkgs.turtle ])"

{-# LANGUAGE OverloadedStrings #-}
import Turtle

main = sh $ do
  homedir <- home
  echo $ "From nix-shell haskell script - Home dir is: " <> repr homedir
```

2. Then setup proper permissions:

```bash
chmod u+x haskell-script.sh
```

3. Finally, run the script:
```bash
./haskell-script.sh 
```

**Comment by mirko-plowtech** [comment]
closed by https://github.com/emeks-studio/colorin-colorado/commit/4e428f571d51fda257026e128a920e8e78b0dc2c
